// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_ACTIVE  AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_BLOCKED AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_DELETED AccountStatus = 2
)

var AccountStatus_name = map[int32]string{
	0: "ACCOUNT_STATUS_ACTIVE",
	1: "ACCOUNT_STATUS_BLOCKED",
	2: "ACCOUNT_STATUS_DELETED",
}

var AccountStatus_value = map[string]int32{
	"ACCOUNT_STATUS_ACTIVE":  0,
	"ACCOUNT_STATUS_BLOCKED": 1,
	"ACCOUNT_STATUS_DELETED": 2,
}

func (x AccountStatus) String() string {
	return proto.EnumName(AccountStatus_name, int32(x))
}

func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type UserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserResponse struct {
	Id                   *UserID       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string        `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status               AccountStatus `protobuf:"varint,3,opt,name=status,proto3,enum=user.AccountStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() *UserID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_ACCOUNT_STATUS_ACTIVE
}

type UserID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Id                   *UserID       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               AccountStatus `protobuf:"varint,2,opt,name=status,proto3,enum=user.AccountStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() *UserID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpdateRequest) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_ACCOUNT_STATUS_ACTIVE
}

type FindFilter struct {
	Ids                  []string        `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Statuses             []AccountStatus `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=user.AccountStatus" json:"statuses,omitempty"`
	Emails               []string        `protobuf:"bytes,3,rep,name=emails,proto3" json:"emails,omitempty"`
	Limit                int32           `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FindFilter) Reset()         { *m = FindFilter{} }
func (m *FindFilter) String() string { return proto.CompactTextString(m) }
func (*FindFilter) ProtoMessage()    {}
func (*FindFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *FindFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilter.Unmarshal(m, b)
}
func (m *FindFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilter.Marshal(b, m, deterministic)
}
func (m *FindFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilter.Merge(m, src)
}
func (m *FindFilter) XXX_Size() int {
	return xxx_messageInfo_FindFilter.Size(m)
}
func (m *FindFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilter.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilter proto.InternalMessageInfo

func (m *FindFilter) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindFilter) GetStatuses() []AccountStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *FindFilter) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *FindFilter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterEnum("user.AccountStatus", AccountStatus_name, AccountStatus_value)
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*UserID)(nil), "user.UserID")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
	proto.RegisterType((*FindFilter)(nil), "user.FindFilter")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xdf, 0x6e, 0xa2, 0x40,
	0x14, 0xc6, 0xe5, 0x8f, 0x64, 0x3d, 0xfe, 0x09, 0x7b, 0x76, 0xd7, 0xb0, 0x66, 0x2f, 0x36, 0x6c,
	0xb2, 0xd9, 0x6c, 0x13, 0x6b, 0xf5, 0x09, 0x28, 0x60, 0x62, 0x6a, 0x6a, 0x82, 0xd0, 0x8b, 0xde,
	0x18, 0x95, 0xb9, 0x20, 0x41, 0xb1, 0x30, 0x5c, 0xf6, 0xfd, 0xfa, 0x58, 0x9d, 0x61, 0xa8, 0x48,
	0xa3, 0xed, 0x15, 0x73, 0xe6, 0xfb, 0xe6, 0x77, 0x66, 0xbe, 0x03, 0x40, 0x9e, 0x91, 0x74, 0x78,
	0x48, 0x13, 0x9a, 0xa0, 0xca, 0xd7, 0xe6, 0x1f, 0x68, 0x07, 0xec, 0xeb, 0x91, 0xa7, 0x9c, 0x64,
	0x14, 0xbf, 0x43, 0x93, 0xec, 0xd6, 0x51, 0x6c, 0x48, 0xbf, 0xa5, 0x7f, 0x2d, 0x4f, 0x14, 0x66,
	0x02, 0x1d, 0x61, 0xca, 0x0e, 0xc9, 0x3e, 0x23, 0xf8, 0x0b, 0xe4, 0x28, 0x2c, 0x2c, 0xed, 0x71,
	0x67, 0x58, 0x30, 0xb9, 0x3e, 0x73, 0x3c, 0xb6, 0x5f, 0x31, 0xe4, 0x13, 0x06, 0x5e, 0x81, 0x96,
	0xd1, 0x35, 0xcd, 0x33, 0x43, 0x61, 0xdb, 0xbd, 0xf1, 0x37, 0x71, 0xce, 0xda, 0x6e, 0x93, 0x7c,
	0x4f, 0x97, 0x85, 0xe4, 0x95, 0x16, 0xd3, 0x00, 0x4d, 0x00, 0xb1, 0x77, 0x6c, 0xd5, 0xe2, 0x70,
	0xf3, 0x11, 0xba, 0xc1, 0x21, 0x5c, 0x53, 0xf2, 0x76, 0xe3, 0x8f, 0xef, 0x52, 0x75, 0x95, 0x3f,
	0xef, 0xfa, 0x0c, 0x30, 0x8d, 0xf6, 0xe1, 0x34, 0x8a, 0x29, 0x49, 0x51, 0x07, 0x25, 0x0a, 0x33,
	0x46, 0x56, 0x58, 0x6b, 0xbe, 0xc4, 0x6b, 0xf8, 0x22, 0x9c, 0x84, 0xe3, 0x94, 0x4b, 0xb8, 0xa3,
	0x09, 0xfb, 0xa0, 0x15, 0x8f, 0xe7, 0x6f, 0xe6, 0x94, 0xb2, 0xe2, 0x09, 0xc5, 0xd1, 0x2e, 0xa2,
	0x86, 0xca, 0x2e, 0xd5, 0xf4, 0x44, 0xf1, 0x7f, 0x03, 0xdd, 0x1a, 0x08, 0x7f, 0xc2, 0x0f, 0xcb,
	0xb6, 0x17, 0xc1, 0xbd, 0xbf, 0x5a, 0xfa, 0x96, 0x1f, 0x2c, 0x57, 0x96, 0xed, 0xcf, 0x1e, 0x5c,
	0xbd, 0x81, 0x03, 0xe8, 0xbf, 0x93, 0x6e, 0xe7, 0x0b, 0xfb, 0xce, 0x75, 0x74, 0xe9, 0x8c, 0xe6,
	0xb8, 0x73, 0xd7, 0x67, 0x9a, 0x3c, 0x7e, 0x91, 0x40, 0xe5, 0xf1, 0xe0, 0x0d, 0x68, 0x76, 0x4a,
	0x58, 0x8e, 0xf8, 0xb5, 0x0a, 0xad, 0xcc, 0x74, 0x80, 0xa7, 0x5b, 0x62, 0xe6, 0x66, 0x03, 0xff,
	0x82, 0xe6, 0x90, 0x98, 0xb0, 0x23, 0xb5, 0x9c, 0x07, 0xb5, 0x8a, 0xf9, 0x26, 0x6c, 0x78, 0xc5,
	0x88, 0xb0, 0x8c, 0xa7, 0x36, 0xb0, 0x0b, 0xf0, 0x11, 0xa8, 0x3c, 0x7b, 0xd4, 0x85, 0x5a, 0xcd,
	0xe1, 0xbc, 0x7f, 0x24, 0x6d, 0xb4, 0xe2, 0x37, 0x9e, 0xbc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xde,
	0x34, 0xfe, 0x86, 0xd4, 0x02, 0x00, 0x00,
}
