// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_ACTIVE  AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_BLOCKED AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_DELETED AccountStatus = 2
)

var AccountStatus_name = map[int32]string{
	0: "ACCOUNT_STATUS_ACTIVE",
	1: "ACCOUNT_STATUS_BLOCKED",
	2: "ACCOUNT_STATUS_DELETED",
}

var AccountStatus_value = map[string]int32{
	"ACCOUNT_STATUS_ACTIVE":  0,
	"ACCOUNT_STATUS_BLOCKED": 1,
	"ACCOUNT_STATUS_DELETED": 2,
}

func (x AccountStatus) String() string {
	return proto.EnumName(AccountStatus_name, int32(x))
}

func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type CreateRequest struct {
	Meta                 []*UserMeta `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetMeta() []*UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type UserMeta struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (m *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(m, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

func (m *UserMeta) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UserMeta) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type UserResponse struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               AccountStatus `protobuf:"varint,2,opt,name=status,proto3,enum=user.AccountStatus" json:"status,omitempty"`
	Meta                 []*UserMeta   `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_ACCOUNT_STATUS_ACTIVE
}

func (m *UserResponse) GetMeta() []*UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type FindFilter struct {
	Ids                  []string        `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Statuses             []AccountStatus `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=user.AccountStatus" json:"statuses,omitempty"`
	MetaFields           []*UserMeta     `protobuf:"bytes,3,rep,name=metaFields,proto3" json:"metaFields,omitempty"`
	Limit                int32           `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32           `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FindFilter) Reset()         { *m = FindFilter{} }
func (m *FindFilter) String() string { return proto.CompactTextString(m) }
func (*FindFilter) ProtoMessage()    {}
func (*FindFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *FindFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilter.Unmarshal(m, b)
}
func (m *FindFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilter.Marshal(b, m, deterministic)
}
func (m *FindFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilter.Merge(m, src)
}
func (m *FindFilter) XXX_Size() int {
	return xxx_messageInfo_FindFilter.Size(m)
}
func (m *FindFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilter.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilter proto.InternalMessageInfo

func (m *FindFilter) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindFilter) GetStatuses() []AccountStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *FindFilter) GetMetaFields() []*UserMeta {
	if m != nil {
		return m.MetaFields
	}
	return nil
}

func (m *FindFilter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindFilter) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               AccountStatus `protobuf:"varint,2,opt,name=status,proto3,enum=user.AccountStatus" json:"status,omitempty"`
	MetaFields           []*UserMeta   `protobuf:"bytes,3,rep,name=metaFields,proto3" json:"metaFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_ACCOUNT_STATUS_ACTIVE
}

func (m *UpdateRequest) GetMetaFields() []*UserMeta {
	if m != nil {
		return m.MetaFields
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.AccountStatus", AccountStatus_name, AccountStatus_value)
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*UserMeta)(nil), "user.UserMeta")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*FindFilter)(nil), "user.FindFilter")
	proto.RegisterType((*DeleteRequest)(nil), "user.DeleteRequest")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xdb, 0x6a, 0xdb, 0x40,
	0x10, 0x8d, 0x6c, 0xd9, 0xa4, 0x93, 0xda, 0x98, 0x69, 0x1a, 0x1c, 0xbf, 0xb4, 0xe8, 0x29, 0xa4,
	0x20, 0x07, 0xfb, 0x0b, 0x54, 0xd9, 0xa6, 0xa5, 0x69, 0x03, 0xb2, 0xdc, 0xd7, 0x20, 0x47, 0xe3,
	0x20, 0xaa, 0x68, 0x5d, 0xed, 0xaa, 0x60, 0xe8, 0x2f, 0xf5, 0x7b, 0xfa, 0x3b, 0xdd, 0x8b, 0x14,
	0x57, 0x41, 0x0e, 0xe4, 0x45, 0xcc, 0xce, 0x9c, 0x3d, 0x67, 0x66, 0xcf, 0x08, 0xa0, 0xe0, 0x94,
	0xbb, 0xdb, 0x9c, 0x09, 0x86, 0xb6, 0x8a, 0x47, 0xe7, 0xf7, 0x8c, 0xdd, 0xa7, 0x34, 0xd6, 0xb9,
	0x75, 0xb1, 0x19, 0x47, 0xd9, 0xce, 0x00, 0x9c, 0x29, 0xf4, 0xfc, 0x9c, 0x22, 0x41, 0x01, 0xfd,
	0x2c, 0x88, 0x0b, 0x74, 0xc0, 0x7e, 0x20, 0x11, 0x0d, 0xad, 0xf7, 0xed, 0x8b, 0x93, 0x49, 0xdf,
	0xd5, 0x64, 0x2b, 0xf9, 0xf9, 0x2a, 0xb3, 0x81, 0xae, 0x39, 0x9f, 0xe0, 0xb8, 0xca, 0xe0, 0x00,
	0xda, 0x3f, 0x68, 0x27, 0xe1, 0xd6, 0xc5, 0xab, 0x40, 0x85, 0x78, 0x09, 0x9d, 0x5f, 0x51, 0x5a,
	0xd0, 0xb0, 0x25, 0x73, 0x27, 0x93, 0x53, 0xd7, 0xa8, 0xbb, 0x95, 0xba, 0xeb, 0x65, 0xbb, 0xc0,
	0x40, 0x1c, 0x06, 0xaf, 0x15, 0x53, 0x40, 0x7c, 0xcb, 0x32, 0x4e, 0xd8, 0x87, 0x56, 0x12, 0x97,
	0x64, 0x32, 0xc2, 0x0f, 0xd0, 0xe5, 0x22, 0x12, 0x05, 0xd7, 0x64, 0xfd, 0xc9, 0x1b, 0xd3, 0x8f,
	0x77, 0x77, 0xc7, 0x8a, 0x4c, 0x2c, 0x75, 0x29, 0x28, 0x21, 0x8f, 0xad, 0xb7, 0x9f, 0x69, 0xfd,
	0x8f, 0x05, 0xb0, 0x48, 0xb2, 0x78, 0x91, 0xa4, 0x82, 0x72, 0xd5, 0x7d, 0x12, 0x73, 0x3d, 0xac,
	0xec, 0x5e, 0x86, 0x38, 0x86, 0x63, 0x43, 0x47, 0x4a, 0xb3, 0x7d, 0x48, 0xf3, 0x11, 0x84, 0x2e,
	0x80, 0x62, 0x5e, 0x24, 0x94, 0x4a, 0xa6, 0x66, 0xed, 0xff, 0x10, 0x78, 0x0a, 0x9d, 0x34, 0x79,
	0x48, 0xc4, 0xd0, 0x96, 0x13, 0x75, 0x02, 0x73, 0xc0, 0x33, 0xe8, 0xb2, 0xcd, 0x86, 0x93, 0x18,
	0x76, 0x74, 0xba, 0x3c, 0x39, 0xef, 0xa0, 0x37, 0xa3, 0x94, 0xf6, 0xfe, 0x3c, 0x79, 0x21, 0xe7,
	0x37, 0xf4, 0x56, 0xdb, 0x38, 0x3a, 0x08, 0x78, 0xd9, 0x13, 0xbe, 0x70, 0x98, 0xcb, 0x35, 0xf4,
	0x6a, 0x44, 0x78, 0x0e, 0x6f, 0x3d, 0xdf, 0xbf, 0x59, 0x7d, 0x0b, 0x6f, 0x97, 0xa1, 0x17, 0xae,
	0x96, 0xb7, 0x9e, 0x1f, 0x7e, 0xfe, 0x3e, 0x1f, 0x1c, 0xe1, 0x08, 0xce, 0x9e, 0x94, 0x3e, 0x5e,
	0xdf, 0xf8, 0x5f, 0xe6, 0xb3, 0x81, 0xd5, 0x50, 0x9b, 0xcd, 0xaf, 0xe7, 0xa1, 0xac, 0xb5, 0x26,
	0x7f, 0x2d, 0xb0, 0x95, 0x38, 0x4e, 0xa1, 0x6b, 0x76, 0x15, 0xcb, 0x19, 0x6a, 0x9b, 0x3b, 0xc2,
	0x7d, 0x9f, 0xd5, 0x3e, 0x39, 0x47, 0x78, 0x05, 0xb6, 0xf2, 0x1b, 0x07, 0xa6, 0xba, 0xf7, 0xbe,
	0x19, 0x7f, 0x65, 0x29, 0x19, 0xf3, 0xe4, 0x95, 0x4c, 0xcd, 0x80, 0x03, 0x32, 0xf2, 0x92, 0xb1,
	0xa1, 0xba, 0x54, 0x33, 0xa5, 0xf9, 0xd2, 0xba, 0xab, 0x7f, 0x89, 0xe9, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0x51, 0x88, 0x99, 0xb2, 0x03, 0x00, 0x00,
}
