// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*UserResponse, error)
	Find(ctx context.Context, in *FindFilter, opts ...client.CallOption) (User_FindService, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*UserResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UserResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "User.Create", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Find(ctx context.Context, in *FindFilter, opts ...client.CallOption) (User_FindService, error) {
	req := c.c.NewRequest(c.name, "User.Find", &FindFilter{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &userServiceFind{stream}, nil
}

type User_FindService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*UserResponse, error)
}

type userServiceFind struct {
	stream client.Stream
}

func (x *userServiceFind) Close() error {
	return x.stream.Close()
}

func (x *userServiceFind) Context() context.Context {
	return x.stream.Context()
}

func (x *userServiceFind) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *userServiceFind) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *userServiceFind) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "User.Delete", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "User.Update", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Create(context.Context, *CreateRequest, *UserResponse) error
	Find(context.Context, *FindFilter, User_FindStream) error
	Delete(context.Context, *DeleteRequest, *UserResponse) error
	Update(context.Context, *UpdateRequest, *UserResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Create(ctx context.Context, in *CreateRequest, out *UserResponse) error
		Find(ctx context.Context, stream server.Stream) error
		Delete(ctx context.Context, in *DeleteRequest, out *UserResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UserResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Create(ctx context.Context, in *CreateRequest, out *UserResponse) error {
	return h.UserHandler.Create(ctx, in, out)
}

func (h *userHandler) Find(ctx context.Context, stream server.Stream) error {
	m := new(FindFilter)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.UserHandler.Find(ctx, m, &userFindStream{stream})
}

type User_FindStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*UserResponse) error
}

type userFindStream struct {
	stream server.Stream
}

func (x *userFindStream) Close() error {
	return x.stream.Close()
}

func (x *userFindStream) Context() context.Context {
	return x.stream.Context()
}

func (x *userFindStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *userFindStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *userFindStream) Send(m *UserResponse) error {
	return x.stream.Send(m)
}

func (h *userHandler) Delete(ctx context.Context, in *DeleteRequest, out *UserResponse) error {
	return h.UserHandler.Delete(ctx, in, out)
}

func (h *userHandler) Update(ctx context.Context, in *UpdateRequest, out *UserResponse) error {
	return h.UserHandler.Update(ctx, in, out)
}
