// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// `AccountStatus` represents list of available account statuses.
type AccountStatus int32

const (
	AccountStatus_PENDING AccountStatus = 0
	AccountStatus_ACTIVE  AccountStatus = 1
	AccountStatus_BLOCKED AccountStatus = 2
	AccountStatus_DELETED AccountStatus = 3
)

var AccountStatus_name = map[int32]string{
	0: "PENDING",
	1: "ACTIVE",
	2: "BLOCKED",
	3: "DELETED",
}

var AccountStatus_value = map[string]int32{
	"PENDING": 0,
	"ACTIVE":  1,
	"BLOCKED": 2,
	"DELETED": 3,
}

func (x AccountStatus) String() string {
	return proto.EnumName(AccountStatus_name, int32(x))
}

func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

// `CreateRequest` represents request message to create a new user.
type CreateRequest struct {
	Meta                 *_struct.Struct `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetMeta() *_struct.Struct {
	if m != nil {
		return m.Meta
	}
	return nil
}

// `UserResponse` represents user response model.
type UserResponse struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               AccountStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=user.AccountStatus" json:"status,omitempty"`
	Meta                 *_struct.Struct `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_PENDING
}

func (m *UserResponse) GetMeta() *_struct.Struct {
	if m != nil {
		return m.Meta
	}
	return nil
}

// `FindFilter` represents filter model for finding users.
type FindFilter struct {
	Ids                  []string          `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Statuses             []AccountStatus   `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=user.AccountStatus" json:"statuses,omitempty"`
	MetaPatterns         map[string]string `protobuf:"bytes,3,rep,name=metaPatterns,proto3" json:"metaPatterns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Limit                int64             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64             `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FindFilter) Reset()         { *m = FindFilter{} }
func (m *FindFilter) String() string { return proto.CompactTextString(m) }
func (*FindFilter) ProtoMessage()    {}
func (*FindFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *FindFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilter.Unmarshal(m, b)
}
func (m *FindFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilter.Marshal(b, m, deterministic)
}
func (m *FindFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilter.Merge(m, src)
}
func (m *FindFilter) XXX_Size() int {
	return xxx_messageInfo_FindFilter.Size(m)
}
func (m *FindFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilter.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilter proto.InternalMessageInfo

func (m *FindFilter) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindFilter) GetStatuses() []AccountStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *FindFilter) GetMetaPatterns() map[string]string {
	if m != nil {
		return m.MetaPatterns
	}
	return nil
}

func (m *FindFilter) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindFilter) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// `DeleteRequest` represents delete user request model.
type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// `UpdateRequest` represents update user request model.
type UpdateRequest struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               AccountStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=user.AccountStatus" json:"status,omitempty"`
	MetaFields           *_struct.Struct `protobuf:"bytes,3,opt,name=metaFields,proto3" json:"metaFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_PENDING
}

func (m *UpdateRequest) GetMetaFields() *_struct.Struct {
	if m != nil {
		return m.MetaFields
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.AccountStatus", AccountStatus_name, AccountStatus_value)
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*FindFilter)(nil), "user.FindFilter")
	proto.RegisterMapType((map[string]string)(nil), "user.FindFilter.MetaPatternsEntry")
	proto.RegisterType((*DeleteRequest)(nil), "user.DeleteRequest")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x5b, 0x4f, 0x13, 0x41,
	0x14, 0x66, 0x2f, 0x2c, 0x72, 0xa0, 0x64, 0x3d, 0x1a, 0x6c, 0x56, 0x13, 0xcd, 0x3e, 0x19, 0x4d,
	0xb6, 0x58, 0x1e, 0x34, 0xc6, 0xc4, 0x40, 0xbb, 0x35, 0x44, 0x04, 0x32, 0x80, 0xef, 0x4b, 0xf7,
	0x94, 0x6c, 0xdc, 0xee, 0xd6, 0x9d, 0x59, 0x63, 0x7f, 0x80, 0x3e, 0xfa, 0x9b, 0x9d, 0x4b, 0x0b,
	0xdd, 0x02, 0x11, 0xdf, 0xe6, 0xcc, 0x7c, 0x97, 0x33, 0xf3, 0x9d, 0x01, 0xa8, 0x39, 0x55, 0xd1,
	0xa4, 0x2a, 0x45, 0x89, 0xae, 0x5a, 0x07, 0xcf, 0x2e, 0xcb, 0xf2, 0x32, 0xa7, 0x8e, 0xde, 0xbb,
	0xa8, 0x47, 0x1d, 0x2e, 0xaa, 0x7a, 0x28, 0x0c, 0x26, 0x78, 0xba, 0x7c, 0x4a, 0xe3, 0x89, 0x98,
	0x9a, 0xc3, 0xf0, 0x03, 0xb4, 0x7a, 0x15, 0x25, 0x82, 0x18, 0x7d, 0xaf, 0x89, 0x0b, 0x7c, 0x0d,
	0xee, 0x98, 0x44, 0xd2, 0xb6, 0x5e, 0x58, 0x2f, 0x37, 0xba, 0x4f, 0x22, 0x43, 0x8e, 0xe6, 0xe4,
	0xe8, 0x54, 0x4b, 0x33, 0x0d, 0x0a, 0x7f, 0xc2, 0xe6, 0xb9, 0x6c, 0x80, 0x11, 0x9f, 0x94, 0x05,
	0x27, 0xdc, 0x02, 0x3b, 0x4b, 0x35, 0x75, 0x9d, 0xc9, 0x95, 0x14, 0xf3, 0xb8, 0x48, 0x44, 0xcd,
	0xdb, 0xb6, 0xdc, 0xdb, 0xea, 0x3e, 0x8a, 0x74, 0xef, 0x7b, 0xc3, 0x61, 0x59, 0x17, 0xe2, 0x54,
	0x1f, 0xb1, 0x19, 0xe4, 0xca, 0xd9, 0xb9, 0x8f, 0xf3, 0x6f, 0x1b, 0x60, 0x90, 0x15, 0xe9, 0x20,
	0xcb, 0x05, 0x55, 0xe8, 0x83, 0x93, 0xa5, 0x5c, 0x3a, 0x3b, 0xd2, 0x59, 0x2d, 0xb1, 0x03, 0x0f,
	0x8c, 0x2e, 0x29, 0x73, 0xe7, 0x2e, 0xf3, 0x2b, 0x10, 0x0e, 0x60, 0x53, 0x29, 0x9f, 0x24, 0x42,
	0x0a, 0x16, 0x5c, 0xb6, 0xe1, 0xc8, 0x36, 0x42, 0x43, 0xba, 0xb6, 0x8a, 0xbe, 0x2c, 0x80, 0xe2,
	0x42, 0x54, 0x53, 0xd6, 0xe0, 0xe1, 0x63, 0x58, 0xcd, 0xb3, 0x71, 0x26, 0xda, 0xae, 0xbc, 0x87,
	0xc3, 0x4c, 0x81, 0xdb, 0xe0, 0x95, 0xa3, 0x11, 0x27, 0xd1, 0x5e, 0xd5, 0xdb, 0xb3, 0x2a, 0xf8,
	0x08, 0x0f, 0x6f, 0x08, 0xaa, 0xdb, 0x7c, 0xa3, 0xe9, 0xec, 0x1d, 0xd5, 0x52, 0x89, 0xfe, 0x48,
	0xf2, 0x9a, 0xf4, 0x3b, 0xae, 0x33, 0x53, 0xbc, 0xb7, 0xdf, 0x59, 0xe1, 0x73, 0x68, 0xf5, 0x29,
	0xa7, 0xeb, 0x00, 0x97, 0x32, 0x08, 0x7f, 0x59, 0xd0, 0x3a, 0x9f, 0xa4, 0xc9, 0x9d, 0x88, 0xff,
	0x4b, 0xe9, 0x2d, 0x80, 0xba, 0xee, 0x20, 0xa3, 0x3c, 0xe5, 0xff, 0xca, 0x6a, 0x01, 0xfa, 0x6a,
	0x1f, 0x5a, 0x0d, 0x45, 0xdc, 0x80, 0xb5, 0x93, 0xf8, 0xa8, 0x7f, 0x70, 0xf4, 0xc9, 0x5f, 0x41,
	0x00, 0x6f, 0xaf, 0x77, 0x76, 0xf0, 0x35, 0xf6, 0x2d, 0x75, 0xb0, 0x7f, 0x78, 0xdc, 0xfb, 0x1c,
	0xf7, 0x7d, 0x5b, 0x15, 0xfd, 0xf8, 0x30, 0x3e, 0x93, 0x85, 0xd3, 0xfd, 0x63, 0x83, 0xab, 0x06,
	0x0e, 0x77, 0xc1, 0x33, 0x63, 0x8b, 0xb3, 0x66, 0x1b, 0x43, 0x1c, 0xa0, 0xd9, 0x5c, 0x9c, 0xcd,
	0x70, 0x05, 0x77, 0xc0, 0x55, 0x39, 0xa2, 0xbf, 0x9c, 0xe9, 0xed, 0xf8, 0x1d, 0x0b, 0xdf, 0xc0,
	0x9a, 0x42, 0x1d, 0x17, 0x74, 0x5f, 0x92, 0x7c, 0x1f, 0xcf, 0xe4, 0x31, 0xef, 0xac, 0x91, 0x4e,
	0xb0, 0x7d, 0xe3, 0xa9, 0x62, 0xf5, 0x1b, 0x25, 0x51, 0x5e, 0xc9, 0xc4, 0x34, 0x27, 0x36, 0x42,
	0xbb, 0xdd, 0xed, 0xc2, 0xd3, 0x32, 0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x4c, 0xda,
	0x87, 0x14, 0x04, 0x00, 0x00,
}
